### ISSUE TITLE
Licensing Issues with Live2D Files

### ISSUE THREAD

**Issue by HigasaMitsue** [RavioliMavioli/archlive2d#7]
First off, thank you so much for releasing your PSD and Inochi2D files as CC0, they're a wonderful contribution to the overall VTuber community.

Unfortunately, I believe CC0 cannot be applied to the Live2D version of the files due to Cubism's Software License Agreement:

> 7.4 If this Agreement is terminated pursuant to Section 7.1, the Customer shall promptly destroy the Software, all copies thereof, and all Derivative Work including the Output Files and any other derivatives arising from use of the Software.

https://www.live2d.jp/en/terms/live2D-editor-software-license-agreement/

There are other relevant clauses, but `7.4` alone is already incompatible with CC0, as it imposes an additional restriction - Live2D's ability to destroy all copies of Output Files via termination of their agreement. `7.1` further details ways in which the Output Files cannot be used, which again prevents it from being licensed as CC0:

<details><summary>Live2D Software License Agreement 7.1</summary>
7.1 Cancellation

If any Customers fall under any of the cases set forth in the respective items below (when the Customers are corporations or any other organizations, including their officers and the Representatives), Live2D may immediately cancel this Agreement without giving notice to the Customers.

7.1.1 If any Customers engage in the prohibited acts stipulated under Section 5. Restriction and Requirements;

7.1.2 If any Customers breach the provisions of this Agreement and fail to correct the breach within a reasonable period upon notice to them;

7.1.3 If any Customers wrongfully damage the interests of Live2D’s other customers or clients or if any Customers impair the trust, social reputation or status of Live2D or hinder the operations of Live2D;

7.1.4 If it is found that any Customers are or have been antisocial forces (organized crime groups, corporate racketeers and other antisocial organizations or persons) or if it is found that any Customers have or had any capital, business, personal or other relationships with antisocial forces for any purposes;

7.1.5 If any Customers are subject to the revocation of a business permit, suspension of business or other disposition by the competent authorities;

7.1.6 If any Customers suspend payment or become insolvent, or if any Customers dishonor a bill or check;

7.1.7 If any third party files a petition against any Customers for attachment, provisional seizure, provisional disposition or auction, or if any Customers are subject to the disposition of delinquency in the payment of taxes and other public charges;

7.1.8 If a petition is filed against any Customers for the institution of the proceedings for bankruptcy, civil rehabilitation, corporate reorganization or special liquidation, or if any Customers file such a petition;

7.1.9 If any Customers pass a resolution of dissolution, company split, business transfer or merger;

7.1.10 If upon any substantial change in the assets or credit standing of any Customers, it is considered that it may be difficult for them to perform the obligations under this Agreement;

7.1.11 If any Customers violate this Agreement or infringe the intellectual property rights to the Software and cause damage to Live2D; and

7.1.12 If any cases arise that are similar to those described in the respective items above.
</details>

This does not impact the PSD nor the Inochi2D files, but all Output Files as declared by Live2D need a different license, subservient to the Software License Agreement.

**Comment by RavioliMavioli** [comment]
Seems like Inochi file and krita file are the only way to go. Anyway thank you very much ^^
